name: manuflow_utils
description: A Flutter package for an awesome ManuFlow
version: 0.1.0+1

environment:
  sdk: "^3.3.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ">=5.1.0 <7.0.0"

repository: https://github.com/ZsoltFischer/manuflow_utils

